### ISSUE TITLE
Error after running config.sh: "fatal error: dds/dds.h: No such file or directory"

### ISSUE THREAD

**Issue by schornakj** [eclipse-zenoh/zenoh-plugin-dds#25]
OS: Ubuntu 20.04
ROS: Foxy, installed from binaries
I installed Rust using `rustup` as recommended in this repo's README.

After cloning the repo and sourcing `/opt/ros/foxy/setup.bash`, I ran the `config.sh` script, but I encounter an error while building some dependencies:

```
In file included from /home/jschornak/zenoh-plugin-dds/deps/cyclocut/src/cdds_blob.c:4:
/home/jschornak/zenoh-plugin-dds/deps/cyclocut/./include/cdds/cdds_util.h:5:10: fatal error: dds/dds.h: No such file or directory
 #include "dds/dds.h"
          ^~~~~~~~~~~
compilation terminated.
```
This ultimately causes the Rust build to fail:

```
error: failed to run custom build command for `cyclors v0.1.0 (https://github.com/kydos/cyclors#e20f3df2)`

Caused by:
  process didn't exit successfully: `/home/jschornak/zenoh-plugin-dds/target/release/build/cyclors-7ce0470c2d0478f1/build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-lib=ddsc
  cargo:rustc-link-lib=cdds-util

  --- stderr
  wrapper.h:1:10: fatal error: 'cdds/cdds_util.h' file not found
  wrapper.h:1:10: fatal error: 'cdds/cdds_util.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', /home/jschornak/.cargo/git/checkouts/cyclors-fbee27736ff49651/e20f3df/build.rs:14:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by kydos** [comment]
The commit above, in combination with an update to the CMakeLists.txt of the Cyclocut should solve your problem. Let me know and we'll close the issue if that is the case.

**Comment by schornakj** [comment]
The commit fixed the error I was seeing when running `config.sh`, but I'm still encountering a build failure:

```
$ cargo +nightly build --release --all-targets
   Compiling cyclors v0.1.0 (https://github.com/kydos/cyclors#e20f3df2)
   Compiling pnet_macros v0.27.2
   Compiling http-types v2.10.0
   Compiling uhlc v0.2.1
error: failed to run custom build command for `cyclors v0.1.0 (https://github.com/kydos/cyclors#e20f3df2)`

Caused by:
  process didn't exit successfully: `/home/jschornak/zenoh-plugin-dds/target/release/build/cyclors-7ce0470c2d0478f1/build-script-build` (exit code: 101)
  --- stdout
  cargo:rustc-link-lib=ddsc
  cargo:rustc-link-lib=cdds-util

  --- stderr
  /usr/local/include/cdds/cdds_util.h:5:10: fatal error: 'dds/dds.h' file not found
  /usr/local/include/cdds/cdds_util.h:5:10: fatal error: 'dds/dds.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', /home/jschornak/.cargo/git/checkouts/cyclors-fbee27736ff49651/e20f3df/build.rs:14:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by kydos** [comment]
That's coming from the rust crate that wraps cyclocut (cyclone utils). I'll push a fix shortly.

**Comment by kydos** [comment]
There is a fix in place now,  let me know if that workout.

**Comment by schornakj** [comment]
At risk of peppering you with incremental updates, I now get library linking errors at a later step in the build process. For example:

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/dzd-9eb8bf864a595057.dzd.2gtsdc16-cgu.0.rcgu.o" "-o" "/home/jschornak/zenoh-plugin-dds/target/release/deps/dzd-9eb8bf864a595057" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/jschornak/zenoh-plugin-dds/target/release/deps" "-L" "/usr/local/lib" "-L" "/home/jschornak/zenoh-plugin-dds/target/release/build/ring-ea13a32ccc75dccc/out" "-L" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcfX1dzQ/libring-d9865621216192f6.rlib" "-Wl,--start-group" "-Wl,--end-group" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-ea377e9224b11a8a.rlib" "-Wl,-Bdynamic" "-lcdds-util" "-ldl" "-lddsc" "-lcdds-util" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: cannot find -lddsc
          collect2: error: ld returned 1 exit status
          
error: aborting due to previous error
error: build failed
```

I think it would be good to add this type of environment configuration as an additional job in the CI pipeline, since most ROS2 users will be using package binary distributions.

**Comment by schornakj** [comment]
Looks like this issue is related to the feature request in #23.

**Comment by kydos** [comment]
@schornakj, that error was due to a small issue on the build.rs in the cyclors library. I've pushed a fix for that and some small updates in the config.sh. It seems to work fine for me on a container cyclone installed through ROS2 distribution (make sure to define ROS_DISTRO if you do not have the full ROS installed). Let me know.

**Comment by schornakj** [comment]
I do still get similar build errors using the latest version of the project. I've provided the full logs from my build below.

```
jschornak@jschornak-PickNik-ThinkPad-P15:~/zenoh-plugin-dds$ env | grep CYCLONE
CYCLONE_INCLUDE=/opt/ros/foxy/include
CYCLONE_LIB=/opt/ros/foxy/lib/x86_64-linux-gnu
jschornak@jschornak-PickNik-ThinkPad-P15:~/zenoh-plugin-dds$ env | grep ROS_DISTRO
ROS_DISTRO=foxy
jschornak@jschornak-PickNik-ThinkPad-P15:~$ git clone https://github.com/eclipse-zenoh/zenoh-plugin-dds.git
Cloning into 'zenoh-plugin-dds'...
remote: Enumerating objects: 133, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 293 (delta 60), reused 89 (delta 31), pack-reused 160
Receiving objects: 100% (293/293), 96.01 KiB | 2.09 MiB/s, done.
Resolving deltas: 100% (124/124), done.
jschornak@jschornak-PickNik-ThinkPad-P15:~$ cd zenoh-plugin-dds/
jschornak@jschornak-PickNik-ThinkPad-P15:~/zenoh-plugin-dds$ ./config.sh 
Looking for Cyclone installation at: 
[-.-]
Cyclocut is already installed, skipping installation.
[-.-]
Cargo is already installed, setting up nightly.
info: using existing install for 'nightly-x86_64-unknown-linux-gnu'
info: default toolchain set to 'nightly-x86_64-unknown-linux-gnu'

  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.52.0-nightly (d1206f950 2021-02-15)

info: note that the toolchain 'nightly-2020-12-29-x86_64-unknown-linux-gnu' is currently in use (overridden by '/home/jschornak/zenoh-plugin-dds/rust-toolchain')
Cleaning up.
Done [^_^]

Please set the following environment variables
    export CYCLONE_INCLUDE=/opt/ros/foxy/include
    export CYCLONE_LIB=/opt/ros/foxy/lib/x86_64-linux-gnu

Then run:
    "cargo +nightly build --release --all-targets" 

If you have any questions reach us out on https://gitter.im/atolab/zenoh
jschornak@jschornak-PickNik-ThinkPad-P15:~/zenoh-plugin-dds$ cargo +nightly build --release --all-targets
    Updating crates.io index
    Updating git repository `https://github.com/kydos/cyclors`
    Updating git repository `https://github.com/eclipse-zenoh/zenoh`
  Downloaded idna v0.2.2
  Downloaded async-channel v1.6.1
  Downloaded 2 crates (283.6 KB) in 0.35s
   Compiling libc v0.2.86
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.60
   Compiling version_check v0.9.2
   Compiling memchr v2.3.4
   Compiling value-bag v1.0.0-alpha.6
   Compiling log v0.4.14
   Compiling typenum v1.12.0
   Compiling cfg-if v1.0.0
   Compiling serde_derive v1.0.123
   Compiling serde v1.0.123
   Compiling proc-macro-hack v0.5.19
   Compiling autocfg v1.0.1
   Compiling bitflags v1.2.1
   Compiling once_cell v1.5.2
   Compiling regex-syntax v0.6.22
   Compiling getrandom v0.2.2
   Compiling rustc-serialize v0.3.24
   Compiling term v0.4.6
   Compiling unicode-xid v0.0.3
   Compiling signal-hook v0.3.4
   Compiling getrandom v0.1.16
   Compiling bitflags v0.5.0
   Compiling cc v1.0.66
   Compiling proc-macro-nested v0.1.7
   Compiling futures-core v0.3.12
   Compiling glob v0.2.11
   Compiling pin-project-lite v0.2.4
   Compiling futures-io v0.3.12
   Compiling ryu v1.0.5
   Compiling const_fn v0.4.5
   Compiling cache-padded v1.1.1
   Compiling fastrand v1.4.0
   Compiling parking v2.0.0
   Compiling waker-fn v1.1.0
   Compiling serde_json v1.0.62
   Compiling subtle v2.4.0
   Compiling anyhow v1.0.38
   Compiling event-listener v2.5.1
   Compiling pnet v0.27.2
   Compiling opaque-debug v0.3.0
   Compiling cfg-if v0.1.10
   Compiling ucd-trie v0.1.3
   Compiling http-types v2.10.0
   Compiling ppv-lite86 v0.2.10
   Compiling glob v0.3.0
   Compiling vec-arena v1.0.0
   Compiling pin-utils v0.1.0
   Compiling async-task v4.0.3
   Compiling slab v0.4.2
   Compiling unicode-width v0.1.8
   Compiling matches v0.1.8
   Compiling atomic-waker v1.0.0
   Compiling percent-encoding v2.1.0
   Compiling block-padding v0.2.1
   Compiling quick-error v1.2.3
   Compiling pnet_base v0.27.2
   Compiling spin v0.5.2
   Compiling untrusted v0.7.1
   Compiling lazy_static v1.4.0
   Compiling cpuid-bool v0.2.0
   Compiling strsim v0.8.0
   Compiling termcolor v1.1.2
   Compiling tinyvec_macros v0.1.0
   Compiling vec_map v0.8.2
   Compiling futures-sink v0.3.12
   Compiling bindgen v0.55.1
   Compiling ansi_term v0.11.0
   Compiling rustc-hash v1.1.0
   Compiling hashbrown v0.9.1
   Compiling shlex v0.1.1
   Compiling lazycell v1.3.0
   Compiling peeking_take_while v0.1.2
   Compiling humantime v2.1.0
   Compiling cpuid-bool v0.1.2
   Compiling base64 v0.13.0
   Compiling itoa v0.4.7
   Compiling data-encoding v2.3.2
   Compiling hex v0.4.2
   Compiling base64 v0.12.3
   Compiling keccak v0.1.0
   Compiling infer v0.2.3
   Compiling byteorder v1.4.2
   Compiling home v0.5.3
   Compiling quick-error v2.0.0
   Compiling zplugin-dds v0.5.0-beta.2 (/home/jschornak/zenoh-plugin-dds)
   Compiling fixedbitset v0.2.0
   Compiling libloading v0.6.7
   Compiling generic-array v0.14.4
   Compiling standback v0.2.15
   Compiling time v0.2.25
   Compiling cookie v0.14.3
   Compiling nom v5.1.2
   Compiling thread_local v1.1.3
   Compiling futures-task v0.3.12
   Compiling crossbeam-utils v0.8.1
   Compiling indexmap v1.6.1
   Compiling concurrent-queue v1.2.2
   Compiling async-mutex v1.4.0
   Compiling async-lock v2.3.0
   Compiling pest v2.1.3
   Compiling unicode-bidi v0.3.4
   Compiling textwrap v0.11.0
   Compiling humantime v1.3.0
   Compiling form_urlencoded v1.0.0
   Compiling pnet_macros_support v0.27.2
   Compiling ring v0.16.20
   Compiling clang-sys v1.1.0
   Compiling syntex_pos v0.42.0
   Compiling tinyvec v1.1.1
   Compiling futures-channel v0.3.12
   Compiling async-channel v1.6.1
   Compiling semver-parser v0.10.2
   Compiling unicode-normalization v0.1.17
   Compiling futures-lite v1.11.3
   Compiling aho-corasick v0.7.15
   Compiling quote v1.0.9
   Compiling socket2 v0.3.19
   Compiling signal-hook-registry v1.3.0
   Compiling num_cpus v1.13.0
   Compiling pnet_sys v0.27.2
   Compiling atty v0.2.14
   Compiling dirs-sys-next v0.1.2
   Compiling nix v0.19.1
   Compiling which v3.1.1
   Compiling semver v0.11.0
   Compiling blocking v1.0.2
   Compiling async-executor v1.4.0
   Compiling regex v1.4.3
   Compiling idna v0.2.2
   Compiling petgraph v0.5.1
   Compiling rand_core v0.6.2
   Compiling uuid v0.8.2
   Compiling nb-connect v1.0.3
   Compiling cipher v0.2.5
   Compiling digest v0.9.0
   Compiling crypto-mac v0.10.0
   Compiling block-buffer v0.9.0
   Compiling universal-hash v0.4.0
   Compiling aead v0.3.2
   Compiling rand_core v0.5.1
   Compiling clap v2.33.3
   Compiling dirs-next v2.0.0
   Compiling cexpr v0.4.0
   Compiling rustc_version v0.3.3
   Compiling rand_chacha v0.3.0
   Compiling aes-soft v0.6.4
   Compiling ctr v0.6.0
   Compiling polyval v0.4.5
   Compiling sha2 v0.9.3
   Compiling sha3 v0.9.1
   Compiling hmac v0.10.1
   Compiling shellexpand v2.1.0
   Compiling rand_chacha v0.2.2
   Compiling webpki v0.21.4
   Compiling sct v0.6.0
   Compiling rand v0.8.3
   Compiling aes v0.6.0
   Compiling zenoh-router v0.5.0-beta.8 (https://github.com/eclipse-zenoh/zenoh#195be243)
   Compiling ghash v0.3.1
   Compiling hkdf v0.10.0
   Compiling rand v0.7.3
   Compiling ctor v0.1.19
   Compiling time-macros-impl v0.1.1
   Compiling futures-macro v0.3.12
   Compiling async-attributes v1.1.2
   Compiling thiserror-impl v1.0.23
   Compiling async-trait v0.1.42
   Compiling git-version-macro v0.3.4
   Compiling aes-gcm v0.8.0
   Compiling shared_memory v0.11.4
   Compiling time-macros v0.1.1
   Compiling futures-util v0.3.12
   Compiling git-version v0.3.4
   Compiling thiserror v1.0.23
   Compiling log v0.3.9
   Compiling env_logger v0.7.1
   Compiling polling v2.0.2
   Compiling kv-log-macro v1.0.7
   Compiling rustls v0.19.0
   Compiling env_logger v0.8.3
   Compiling syntex_errors v0.42.0
   Compiling async-io v1.3.1
   Compiling futures-executor v0.3.12
   Compiling async-rustls v0.2.0
   Compiling syntex_syntax v0.42.0
   Compiling async-global-executor v2.0.2
   Compiling async-process v1.0.2
   Compiling futures v0.3.12
   Compiling async-std v1.9.0
   Compiling ipnetwork v0.17.0
   Compiling serde_qs v0.7.2
   Compiling url v2.2.0
   Compiling serde_urlencoded v0.7.0
   Compiling bincode v1.3.1
   Compiling pnet_datalink v0.27.2
   Compiling cyclors v0.1.0 (https://github.com/kydos/cyclors#89f57025)
   Compiling syntex v0.42.2
   Compiling uhlc v0.2.1
   Compiling pnet_macros v0.27.2
   Compiling pnet_packet v0.27.2
   Compiling pnet_transport v0.27.2
   Compiling zenoh-util v0.5.0-beta.8 (https://github.com/eclipse-zenoh/zenoh#195be243)
   Compiling zenoh-protocol v0.5.0-beta.8 (https://github.com/eclipse-zenoh/zenoh#195be243)
   Compiling zenoh v0.5.0-beta.8 (https://github.com/eclipse-zenoh/zenoh#195be243)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/zplugin_dds-85bc55306b8caca8.zplugin_dds.b14otzgf-cgu.0.rcgu.o" "/home/jschornak/zenoh-plugin-dds/target/release/deps/zplugin_dds-85bc55306b8caca8.zplugin_dds.b14otzgf-cgu.1.rcgu.o" "/home/jschornak/zenoh-plugin-dds/target/release/deps/zplugin_dds-85bc55306b8caca8.zplugin_dds.b14otzgf-cgu.2.rcgu.o" "-o" "/home/jschornak/zenoh-plugin-dds/target/release/deps/zplugin_dds-85bc55306b8caca8" "/home/jschornak/zenoh-plugin-dds/target/release/deps/zplugin_dds-85bc55306b8caca8.4sqlvf2c49lbwgdg.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/jschornak/zenoh-plugin-dds/target/release/deps" "-L" "/usr/local/lib" "-L" "/home/jschornak/zenoh-plugin-dds/target/release/build/ring-ea13a32ccc75dccc/out" "-L" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-lcdds-util" "-Wl,-Bstatic" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-f0e2f3090c8b9410.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-bb4c17ac1c56faac.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-65bd06936d117871.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-36e93a55c535bf8b.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-b50c9929f7e246da.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libzenoh-1420eb94259422b3.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libregex-e165a707943c6be9.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libthread_local-18a02b19280f7005.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libregex_syntax-ffc14f4f8e88c926.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libaho_corasick-c32705b9543e76a5.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libgit_version-67e45cb2f32f526f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libzenoh_router-f5527c8401d72b64.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpetgraph-00f9c9d908ea30c1.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfixedbitset-48691e34556fcdf9.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libclap-66abd285ccaa788d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libvec_map-ae37e3e28e7c55e6.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libtextwrap-c665e7aba2515fac.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libunicode_width-8d541a24270c5bdc.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libstrsim-fa2ae2a142ed691e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libatty-de3fd67d2c9cf55e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libansi_term-44d5b9314aeda94a.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libzenoh_protocol-ae76221d3368133d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libbincode-49ccc01aeef90f40.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libbyteorder-909214a55b6c06ee.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libhttp_types-4e474ddae9b374ce.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libserde_qs-bf2846ff987597a6.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libthiserror-1c80700cd0c5e402.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libdata_encoding-7ebdf54b96712044.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libanyhow-0e076c9c3c42fd91.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libserde_urlencoded-559e34f174b45dfb.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libserde_json-8984fb825486443e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libryu-6322974018ccb0b3.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libitoa-9985733af8ac0656.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libindexmap-006cd7472dad5f9a.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libhashbrown-1716f33923b4daee.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libinfer-58b46e52859946f0.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/liburl-a127252693d3867a.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libidna-06bcbd24e62fcd91.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libunicode_normalization-f59a76a27a722457.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libtinyvec-26dec4c2910dc76b.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libtinyvec_macros-535d789e2cfba865.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libunicode_bidi-33df0ae046392039.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libform_urlencoded-7eacaf2573343f39.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libmatches-88af7253bc65c422.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcookie-5a64f8888ea471f6.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libhkdf-161e40d05a53d8a9.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libsha2-1473c00312ea7c3f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcpuid_bool-6c8c9438e985c2eb.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libaes_gcm-4b39e910f0a77154.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libghash-2eb5d69acf228a77.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpolyval-a961d877bfe75a16.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcpuid_bool-b35422a4105586a9.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libuniversal_hash-4fc85de07df16ff2.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libctr-b304f9ec7d274aec.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libaes-8ebffba20298a253.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libaead-104ee442005d9780.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libbase64-5cea588d0d99eb7f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/librand-ab9d9e485c595d40.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/librand_chacha-3b8a15ee0643d37b.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/librand_core-1c73c09ec37eae01.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libgetrandom-bfd8dee3e54b01df.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libtime-d07add96f6951342.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libtime_macros-55df054f15b5fe69.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libstandback-1fe7fe293827e630.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpercent_encoding-f009c05baa584926.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_rustls-073aef6904752647.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/librustls-aa0f17e134c13b4c.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libbase64-04be6a23b716b55b.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libsct-4509f02b122f548d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libwebpki-22b9071e24ced9b0.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libring-33845c80018002b7.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libspin-23782e494d485881.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libuntrusted-8e5a7a74165857c4.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libshared_memory-c865263ed3472c98.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libnix-aa853ecd3ef26b21.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libbitflags-233fcff518b66ba8.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libquick_error-bc7c6f300be918b6.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libuhlc-00263d60bd58ee80.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libhex-353f59de1dd968a7.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libhumantime-3d4076161ad29bde.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libuuid-241d395b8abbc104.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libzenoh_util-b9f45bd8157fc532.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libhome-444a9c453814d927.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpnet-c9d51ad12cbc948d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpnet_transport-0d9ba2c784414688.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpnet_packet-5b3f6e03e16799cd.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpnet_macros_support-c0dc2bb793a538c1.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpnet_datalink-eada0af4add7632b.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpnet_sys-b08655d847ee31dd.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpnet_base-82f7ada4beb24de9.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libipnetwork-f74d971bfc1d7ca7.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libserde-0f4db6b81d954b54.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libshellexpand-33f086b1cbc65d74.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libdirs_next-89d09df7a55b8223.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libdirs_sys_next-1290e2183f1461d6.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/liblibloading-e367bb552e39361c.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libsha3-e63f54092fb86f58.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libkeccak-e3adccdc7d249e71.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libblock_buffer-2344d42bf0d537ad.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libblock_padding-2b4b3b1104ad6451.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libhmac-f4126ddc61904b1e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libdigest-dcd30b3a171458a3.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcrypto_mac-ec6d27bb834963d4.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libsubtle-7d138c867dc64946.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/librand-18ac87b20daec24c.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/librand_chacha-35c3e56a2804a067.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libppv_lite86-6e0c9a5a0bba646d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/librand_core-6b900e674d90d955.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libgetrandom-34dc8b47bd9e424e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libaes_soft-d44ef92c932811fc.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libopaque_debug-1827108be28354fb.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcipher-c095b7a561e0142f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libgeneric_array-8f9bd8b9e9a59db7.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libtypenum-d5809cca3282fc8f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures-0d03578648515853.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_executor-19b693c877668eb0.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_util-c0c277a45e5aa525.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_channel-7d77c494f545df3f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_sink-47aea8d6dad1ca18.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_task-665f4c56ecc944cc.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcyclors-f49bc8ea36669d9e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_std-3b64a5eb3f621a25.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_global_executor-1f5c9da8592f953a.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libblocking-9e6ab60561403bca.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libatomic_waker-2611ba21f4a2c8be.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libnum_cpus-c320c7c10a2b5611.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_mutex-2a8256642a2f0f9a.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_executor-40209d2f1c36ccce.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_task-7be91ac970cc0b6d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libslab-0a7f409eb518a27f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcrossbeam_utils-398bb77df40aa563.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/liblazy_static-4d65e02ed567c9f8.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_process-f890c38bee85e6cf.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libsignal_hook-fa677e0169f741d2.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libsignal_hook_registry-71462552ea3dd1ff.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_io-6338980e63bd895e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libnb_connect-ffb9b9ac1bc95f1d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libsocket2-08585be09f432c76.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libvec_arena-508797ee1a8e777e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpolling-3f604babada356ce.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/liblibc-8a6ac3d2ae92bfd4.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcfg_if-097c2cca0a4265d8.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libonce_cell-075153aa603e6da3.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_lite-55613e6fe812edac.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libmemchr-0948f99be7fed7ac.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfastrand-10b10d8d66acd18d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libwaker_fn-e75bc299296b699f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libparking-4c2449179b8b2485.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_io-330b3dca8605f8c1.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_channel-c8af1ee9406fd010.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libconcurrent_queue-d962150e175952ad.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcache_padded-cc65b9e53b6a8163.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_lock-530122b647396318.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libevent_listener-2365f4279ebfd310.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpin_project_lite-bf98c54733dc580c.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpin_utils-e58dedb027cdaac2.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_core-8f725d466798eca1.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libkv_log_macro-4c25e11e1b3f95aa.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/liblog-631242f3c0dfe288.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libvalue_bag-14eacf982b0d3a04.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcfg_if-56c532915f53a93a.rlib" "-Wl,--start-group" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-6f5658153d127ddd.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-b69e89b2ef7e009e.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-fe971cf9622d0c47.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-9ff49e5df977573d.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-323dea4ee1c9a010.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-f12d17a047776008.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-3d968aa3120f6a27.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-22cd238a7814521c.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-f2c707309e5edc5c.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-6b6b4b2bc151fc5a.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-32b57ee4d7c8dc07.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-d9f2cb19c79e847e.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-3ccc4a4f3013e9ef.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-aa547327a7679d28.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-90996f4879673567.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-9ea09a899c3eda46.rlib" "-Wl,--end-group" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-ea377e9224b11a8a.rlib" "-Wl,-Bdynamic" "-ldl" "-lddsc" "-lcdds-util" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: cannot find -lddsc
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `zplugin-dds`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/dzd-c654e54f199682e9.dzd.8yqv1xyy-cgu.0.rcgu.o" "/home/jschornak/zenoh-plugin-dds/target/release/deps/dzd-c654e54f199682e9.dzd.8yqv1xyy-cgu.1.rcgu.o" "/home/jschornak/zenoh-plugin-dds/target/release/deps/dzd-c654e54f199682e9.dzd.8yqv1xyy-cgu.2.rcgu.o" "-o" "/home/jschornak/zenoh-plugin-dds/target/release/deps/dzd-c654e54f199682e9" "/home/jschornak/zenoh-plugin-dds/target/release/deps/dzd-c654e54f199682e9.2n6avoip11d638w3.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/jschornak/zenoh-plugin-dds/target/release/deps" "-L" "/usr/local/lib" "-L" "/home/jschornak/zenoh-plugin-dds/target/release/build/ring-ea13a32ccc75dccc/out" "-L" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libenv_logger-c1e1383070216d4a.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libtermcolor-db8b72d8230c5500.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-f0e2f3090c8b9410.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-bb4c17ac1c56faac.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-65bd06936d117871.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-36e93a55c535bf8b.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-b50c9929f7e246da.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libzplugin_dds-7d931ebe6307b50b.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libzenoh-1420eb94259422b3.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libregex-e165a707943c6be9.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libthread_local-18a02b19280f7005.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libregex_syntax-ffc14f4f8e88c926.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libaho_corasick-c32705b9543e76a5.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libgit_version-67e45cb2f32f526f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libzenoh_router-f5527c8401d72b64.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpetgraph-00f9c9d908ea30c1.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfixedbitset-48691e34556fcdf9.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libzenoh_protocol-ae76221d3368133d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libbincode-49ccc01aeef90f40.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libbyteorder-909214a55b6c06ee.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libhttp_types-4e474ddae9b374ce.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libserde_qs-bf2846ff987597a6.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libthiserror-1c80700cd0c5e402.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libdata_encoding-7ebdf54b96712044.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libanyhow-0e076c9c3c42fd91.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libserde_urlencoded-559e34f174b45dfb.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libserde_json-8984fb825486443e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libryu-6322974018ccb0b3.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libitoa-9985733af8ac0656.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libindexmap-006cd7472dad5f9a.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libhashbrown-1716f33923b4daee.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libinfer-58b46e52859946f0.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/liburl-a127252693d3867a.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libidna-06bcbd24e62fcd91.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libunicode_normalization-f59a76a27a722457.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libtinyvec-26dec4c2910dc76b.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libtinyvec_macros-535d789e2cfba865.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libunicode_bidi-33df0ae046392039.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libform_urlencoded-7eacaf2573343f39.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libmatches-88af7253bc65c422.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcookie-5a64f8888ea471f6.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libhkdf-161e40d05a53d8a9.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libsha2-1473c00312ea7c3f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcpuid_bool-6c8c9438e985c2eb.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libaes_gcm-4b39e910f0a77154.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libghash-2eb5d69acf228a77.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpolyval-a961d877bfe75a16.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcpuid_bool-b35422a4105586a9.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libuniversal_hash-4fc85de07df16ff2.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libctr-b304f9ec7d274aec.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libaes-8ebffba20298a253.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libaead-104ee442005d9780.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libbase64-5cea588d0d99eb7f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/librand-ab9d9e485c595d40.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/librand_chacha-3b8a15ee0643d37b.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/librand_core-1c73c09ec37eae01.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libgetrandom-bfd8dee3e54b01df.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libtime-d07add96f6951342.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libtime_macros-55df054f15b5fe69.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libstandback-1fe7fe293827e630.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpercent_encoding-f009c05baa584926.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_rustls-073aef6904752647.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/librustls-aa0f17e134c13b4c.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libbase64-04be6a23b716b55b.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libsct-4509f02b122f548d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libwebpki-22b9071e24ced9b0.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libring-33845c80018002b7.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libspin-23782e494d485881.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libuntrusted-8e5a7a74165857c4.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libshared_memory-c865263ed3472c98.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libnix-aa853ecd3ef26b21.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libquick_error-bc7c6f300be918b6.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libuhlc-00263d60bd58ee80.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libhex-353f59de1dd968a7.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libhumantime-3d4076161ad29bde.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libuuid-241d395b8abbc104.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libzenoh_util-b9f45bd8157fc532.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libhome-444a9c453814d927.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpnet-c9d51ad12cbc948d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpnet_transport-0d9ba2c784414688.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpnet_packet-5b3f6e03e16799cd.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpnet_macros_support-c0dc2bb793a538c1.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpnet_datalink-eada0af4add7632b.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpnet_sys-b08655d847ee31dd.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpnet_base-82f7ada4beb24de9.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libipnetwork-f74d971bfc1d7ca7.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libserde-0f4db6b81d954b54.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libshellexpand-33f086b1cbc65d74.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libdirs_next-89d09df7a55b8223.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libdirs_sys_next-1290e2183f1461d6.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/liblibloading-e367bb552e39361c.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libsha3-e63f54092fb86f58.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libkeccak-e3adccdc7d249e71.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libblock_buffer-2344d42bf0d537ad.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libblock_padding-2b4b3b1104ad6451.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libhmac-f4126ddc61904b1e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libdigest-dcd30b3a171458a3.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcrypto_mac-ec6d27bb834963d4.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libsubtle-7d138c867dc64946.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/librand-18ac87b20daec24c.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/librand_chacha-35c3e56a2804a067.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libppv_lite86-6e0c9a5a0bba646d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/librand_core-6b900e674d90d955.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libgetrandom-34dc8b47bd9e424e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libaes_soft-d44ef92c932811fc.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libopaque_debug-1827108be28354fb.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcipher-c095b7a561e0142f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libgeneric_array-8f9bd8b9e9a59db7.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libtypenum-d5809cca3282fc8f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures-0d03578648515853.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_executor-19b693c877668eb0.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_util-c0c277a45e5aa525.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_channel-7d77c494f545df3f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_sink-47aea8d6dad1ca18.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_task-665f4c56ecc944cc.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcyclors-f49bc8ea36669d9e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libclap-66abd285ccaa788d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libvec_map-ae37e3e28e7c55e6.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libtextwrap-c665e7aba2515fac.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libunicode_width-8d541a24270c5bdc.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libstrsim-fa2ae2a142ed691e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libbitflags-233fcff518b66ba8.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libatty-de3fd67d2c9cf55e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libansi_term-44d5b9314aeda94a.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_std-3b64a5eb3f621a25.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_global_executor-1f5c9da8592f953a.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libblocking-9e6ab60561403bca.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libatomic_waker-2611ba21f4a2c8be.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libnum_cpus-c320c7c10a2b5611.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_mutex-2a8256642a2f0f9a.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_executor-40209d2f1c36ccce.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_task-7be91ac970cc0b6d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libslab-0a7f409eb518a27f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcrossbeam_utils-398bb77df40aa563.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/liblazy_static-4d65e02ed567c9f8.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_process-f890c38bee85e6cf.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libsignal_hook-fa677e0169f741d2.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libsignal_hook_registry-71462552ea3dd1ff.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_io-6338980e63bd895e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libnb_connect-ffb9b9ac1bc95f1d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libsocket2-08585be09f432c76.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libvec_arena-508797ee1a8e777e.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpolling-3f604babada356ce.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/liblibc-8a6ac3d2ae92bfd4.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcfg_if-097c2cca0a4265d8.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libonce_cell-075153aa603e6da3.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_lite-55613e6fe812edac.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libmemchr-0948f99be7fed7ac.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfastrand-10b10d8d66acd18d.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libwaker_fn-e75bc299296b699f.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libparking-4c2449179b8b2485.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_io-330b3dca8605f8c1.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_channel-c8af1ee9406fd010.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libconcurrent_queue-d962150e175952ad.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcache_padded-cc65b9e53b6a8163.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libasync_lock-530122b647396318.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libevent_listener-2365f4279ebfd310.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpin_project_lite-bf98c54733dc580c.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libpin_utils-e58dedb027cdaac2.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libfutures_core-8f725d466798eca1.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libkv_log_macro-4c25e11e1b3f95aa.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/liblog-631242f3c0dfe288.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libvalue_bag-14eacf982b0d3a04.rlib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/libcfg_if-56c532915f53a93a.rlib" "-Wl,--start-group" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-6f5658153d127ddd.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-b69e89b2ef7e009e.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-fe971cf9622d0c47.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-9ff49e5df977573d.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-323dea4ee1c9a010.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-f12d17a047776008.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-3d968aa3120f6a27.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-22cd238a7814521c.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-f2c707309e5edc5c.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-6b6b4b2bc151fc5a.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-32b57ee4d7c8dc07.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-d9f2cb19c79e847e.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-3ccc4a4f3013e9ef.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-aa547327a7679d28.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-90996f4879673567.rlib" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-9ea09a899c3eda46.rlib" "-Wl,--end-group" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-ea377e9224b11a8a.rlib" "-Wl,-Bdynamic" "-lcdds-util" "-ldl" "-lddsc" "-lcdds-util" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: cannot find -lddsc
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/jschornak/zenoh-plugin-dds/target/release/deps/dzd-baf6eef1e2f44f30.dzd.ef1wsmik-cgu.0.rcgu.o" "-o" "/home/jschornak/zenoh-plugin-dds/target/release/deps/dzd-baf6eef1e2f44f30" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/jschornak/zenoh-plugin-dds/target/release/deps" "-L" "/usr/local/lib" "-L" "/home/jschornak/zenoh-plugin-dds/target/release/build/ring-ea13a32ccc75dccc/out" "-L" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcsFRhoy/libring-d9865621216192f6.rlib" "-Wl,--start-group" "-Wl,--end-group" "/home/jschornak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-ea377e9224b11a8a.rlib" "-Wl,-Bdynamic" "-lcdds-util" "-ldl" "-lddsc" "-lcdds-util" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: cannot find -lddsc
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: build failed
```

**Comment by schornakj** [comment]
Here is some more info about my specific platform:
```
jschornak@jschornak-PickNik-ThinkPad-P15:~$ uname -a
Linux jschornak-PickNik-ThinkPad-P15 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by kydos** [comment]
Just committed an update to the build.rs to use the CYCLONE_LIB if defined as the library search path. That should solve the issue above, which I guess was the last left to make sure that the DDS plugin builds with a custom cyclone installation, e.g. ROS2.

**Comment by schornakj** [comment]
@kydos The latest version works for me now when building from source. Thank you for the fix!
